### ISSUE TITLE
README.md: Error 403 on Link 6

### ISSUE THREAD

**Issue by gmacario** [maxfields2000/dockerjenkins_tutorial#10]
Opening http://engineering.riotgames.com/news/building-jenkins-inside-ephemeral-docker-container

Returns "Error 403 - Access Denied"

**Comment by maxfields2000** [comment]
The article will go live this week! Until then the link won't work. I wanted to move the branch to main to be ready as we're not quite sure what day we'll go live with the article just yet. I'll leave this issue open until the article is live. Nice catch!

**Comment by gmacario** [comment]
I see... Eager to read the article when publicly available :smile:

**Comment by maxfields2000** [comment]
Article is now live, closing this issue!
