### ISSUE TITLE
no certs folder in repo

### ISSUE THREAD

**Issue by babatundebusari** [maxfields2000/dockerjenkins_tutorial#11]
##### tutorial_07

Any instruction or blog post of how to generate the files under the `certs` folder?
There is no `certs` folder in the repo and no mention of how to generate the files under the folder

Step 33 : COPY certs/ca-key.pem /usr/local/etc/jenkins/certs/ca-key.pem
ERROR: Service 'master' failed to build: lstat certs/ca-key.pem: no such file or directory

Thanks

**Comment by babatundebusari** [comment]
Actually i see in the README file
[by the way the blog post is 404 "http://engineering.riotgames.com/news/ephemeral-docker-build-slaves"]

What about if i have docker-engine on a different computer
Where do i get the cert files from? Lets say Ubuntu 14

So basically i have docker installed on the same host(Ubuntu 14 LTS) i am trying to launch the containers.

**Comment by maxfields2000** [comment]
The tutorial here assumes you're running docker-toolbox from OSX or Windows, hence the certs will be local to your machine.

If you have a docker-host configured someplace else that is using TLS certs, you need to know the specifics of how that host is configured. Those certs will have been generated at t he time that server was made and be located someplace on that machine, possibly in default locations, but you need to consult the docker configuration.

In other words I can't really provide specifics as I don't know how those hosts are set up.  You will need the c ca-key.pem, cert.pem, and client.pem keys.

If you used docker-machine to set up the remote host, the certs you need should be in your ~/.docker/machine/yourmachinenamehere path.

In general the tutorial is for folks who are doing local development, if you have production docker servers you are using I have to assume you know how they are configured.
