### ISSUE TITLE
sh Windows format issue

### ISSUE THREAD

**Issue by djncvc** [maxfields2000/dockerjenkins_tutorial#15]
Just info for Windows users. Cloning on Windows possibly saves plugins.sh (and other .sh) in Windows format. This produces "/bin/sh^M: bad interpreter: No such file or directory" error when build is started. 
I've noticed this when using git clients (SourceTree). 
Maybe install dos2unix ("yum install dos2unix") and "RUN dos2unix plugins.sh" after copying from dockerhost to container to prevent errors when editing these files on Windows (and saving in Windows format). 
Or some script on dockerhost side..

http://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory

**Comment by maxfields2000** [comment]
I should do more testing on Windows but yea, this is a definite challenge with cross platform checkins and shell scripts.  Thanks for the heads up! I'll take ac loser look and see if I can fix somethings.

**Comment by mark-boer** [comment]
That's an issue with Carriage Returns <CR> in windows. By default git on windows adds carriage returns to line-endings. This works oke, when you run it on windows. Docker containers, however, are linux based.

You can disable the carriage returns with:
```
git config --global core.autocrlf false
```
Note that this messes up the newlines when you open the file in notepad. It works fine in sublime though.
