### ISSUE TITLE
Not Compatible with Docker 1.12

### ISSUE THREAD

**Issue by maxfields2000** [maxfields2000/dockerjenkins_tutorial#20]
This error will come from the Jenkins Logs:

"Error in provisioning; template='DockerTemplate{configVersion=2, labelString='testslave', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@52deb96, remoteFsMapping='/home/jenkins', remoteFs='/home/jenkins', instanceCap=1, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@4e4e5b9e, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=jenkins_slave}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='Local Docker' com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}"

It's due to an incompatibility in the Docker-Plugin.  Figured I'd consolidate issues here where it's clear what the root cause is.  I'll be working on testing fixes/updates based on the newer Docker Plugin, called "Yet Another Docker Plugin", very soon!

**Comment by stlbucket** [comment]
https://github.com/docker/docker/blob/master/CHANGELOG.md

what are the odds that 1.13 will just fix the issue?

**Comment by maxfields2000** [comment]
I believe this is now fixed as I'm running it fine locally. So I'm going to close this issue with my next major push (soon tm, so much feedback to incorporate.)

**Comment by SalahAdDin** [comment]
@maxfields2000, I didn't try it in `docket 1.17`yet, but normal `Jenkins` configuration is worked perfectly for me.

**Comment by maxfields2000** [comment]
@SalahAdDin The Jenkins2 folder now contains updates and should work with Docker 1.12 and Docker 1.13 out of the box.  I haven't updated the Tutorial stuff yet because it's tied to the legacy blog. That stuff will still only work with Legacy Docker installs.  Working on a new blog series to update everything but for now the repo has what you need in the Jenkins2 Folder.

**Comment by SalahAdDin** [comment]
@maxfields2000 It have the JNLP ıntegratıon also?
