### ISSUE TITLE
Wrong steps for jenkins2 tutorial

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#28]
Hi man, thanks for you grateful tutorial.

I have a question with the jenkins2 tutorial:

> ```
> Create a new pipeline jenkins job
>     Enter the following for the pipeline script:
> ```
> 
> node ('testslave') {
> 
>   stage 'Stage 1'
>   sh 'echo "Hello World!"'
> 
> }
> 
> ```
> Save job
> Run job
> ```

You put this, but, the script only can we put in a `pipeline` project, but, restringe a project ejecution to `jenkins-slave` volumen only we can configure in a free style project, where we can't use scripts, in this case which correct setup steps?

**Comment by maxfields2000** [comment]
IF you're going to try it in a Jenkins Freestyle project, just set the build job label to "testslave" and things should work.

If using pipeline the proper syntax is now:

```
stage ('Default Slave') {
    node ('testslave') {
        sh 'echo "You have spun up a basic slave!"'
    }
}
```

I also include a test/example job that works out of the box for reference.

**Comment by SalahAdDin** [comment]
@maxfields2000 When will we have your new tutorial?

I can't understand why put two compressed packages in the `data` container.

Whit the new `plugins.sh` official file we can install the plugins like your script.

And your scripts are very awesome :D

**Comment by maxfields2000** [comment]
Sorry it took so long, the new tutorial will be out very soon! Next few days! The blog_refresh branch has the new stuff in it! It'll go to master ASAP after I do final tests.

**Comment by SalahAdDin** [comment]
@maxfields2000 Thank you, it is great!

**Comment by maxfields2000** [comment]
New tutorial changes are now on Master and should be fixed, Blog update goes live in less than 48 hours, so going to close this. Thanks for the feedback and support so far!
