### ISSUE TITLE
{"message":"No such image: jenkins_slave_1:latest"}

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#30]
Hi @maxfields2000 

Thanks for your great tutorial.

I have this error:

```
Sep 28, 2016 7:07:57 AM INFO com.github.kostyasha.yad.DockerCloud provision

Asked to provision load: '1', for: 'docker-slave' label

Sep 28, 2016 7:07:57 AM INFO com.github.kostyasha.yad.DockerCloud provision

Will provision 'jenkins_slave_1', for label: 'docker-slave', in cloud: 'Local DockerHost'

Sep 28, 2016 7:07:57 AM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave

Provisioning 'jenkins_slave_1' number '0' on 'Local DockerHost'; Total containers: '0'

Sep 28, 2016 7:07:57 AM INFO com.github.kostyasha.yad.DockerCloud provisionWithWait

Trying to run container for jenkins_slave_1

Sep 28, 2016 7:07:57 AM SEVERE com.github.kostyasha.yad_docker_java.com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: jenkins_slave_1:latest"}
```

I don't know why, but `Yer another Docker Plugin` can provide the slave container.

I have this in settings:
![seleccion_276](https://cloud.githubusercontent.com/assets/5034215/18905816/864684a8-852a-11e6-99d3-a9cde3242fcf.png)
![seleccion_277](https://cloud.githubusercontent.com/assets/5034215/18905817/8649ebf2-852a-11e6-8570-f134b8a3f5b7.png)

As you can see i put the same docker image than i have in my terminal:
![seleccion_278](https://cloud.githubusercontent.com/assets/5034215/18905847/a6fc8a1c-852a-11e6-90c5-cbb3d20571f5.png)
`jenkins_slave_1`.

I tried with `jenkins_slave` but doesn't works.

I don't know what have i wrong.

I'm using `docker 1.12.1` and `jenkins 2.23`, with lastest `Yer another Docker Plugin`.

And not, isn't connection problem, see:
![seleccion_279](https://cloud.githubusercontent.com/assets/5034215/18905927/fc65e2dc-852a-11e6-8d36-67746c3abb71.png)

I have this `Dockerfile` for `jenkins-slave` image:

```
FROM debian:jessie
MAINTAINER José L. Sandoval A.

# Install all dependencies
RUN echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list

ENV JAVA_VERSION 8u102
ENV JAVA_DEBIAN_VERSION 8u102-b14.1-1~bpo8+1

# see https://bugs.debian.org/775775
# and https://github.com/docker-library/java/issues/19#issuecomment-70546872
ENV CA_CERTIFICATES_JAVA_VERSION 20140324

# Install Essentials and Packages
RUN apt-get update \
    && apt-get install -y gettext git wget \
    openssh-server openjdk-8-jdk="$JAVA_DEBIAN_VERSION"\
    ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION" \
    sudo \
    && apt-get autoremove -y --purge \
    && rm -rf /var/lib/apt/lists/*

RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure

# Create Jenkins User
RUN useradd jenkins -m -s /bin/bash

RUN chown -R jenkins /home/jenkins
RUN chgrp -R jenkins /home/jenkins

# Add the jenkins user to sudoers
RUN echo "jenkins    ALL=(ALL)    ALL" >> etc/sudoers

# Set Name Servers
COPY /files/resolv.conf /etc/resolv.conf

```

Thanks!

**Comment by symball** [comment]
I was facing a similar problem to begin with as, the image name can be defined in three places!

docker-compose.yml - The slave is called jenkins_android
docker-compose ps - cistack_jenkins_android_1 
docker images - cistack_jenkins_android

Ultimately, it was the last one that worked, enjoy!

**Comment by SalahAdDin** [comment]
I have to use the docker images name, right @symball ?

**Comment by symball** [comment]
That's what worked for me @SalahAdDin correct.

> cistack_jenkins_android

**Comment by SalahAdDin** [comment]
And, well, i don't know but now i have and advance, i have serious problems with my custom jenkins image.

I have this in bash: 

``` bash
docker images                                                                                   ✓  4041  00:50:07 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jenkins_master      latest              c0d0eb11f770        About an hour ago   543.8 MB
jenkins_nginx       latest              81e888c9f7ee        4 days ago          356.3 MB
jenkins_data        latest              639e8d5d99e4        4 days ago          123.3 MB
jenkins_slave       latest              66196e8bcfab        4 days ago          626.5 MB
pritunl/archlinux   latest              5cac5ae9cf9e        6 days ago          350.4 MB
jenkins             latest              865c4db528ff        7 days ago          712.3 MB
openjdk             8-jdk               96cddf5ae9f1        7 days ago          640.9 MB
debian              jessie              ddf73f48a05d        7 days ago          123 MB
centos              7                   980e0e4c79ec        3 weeks ago         196.7 MB
 salahaddin@TulipanROG  ~/Proyectos/uzmantech/jenkins   rework ● ?  docker-compose ps                                                                               ✓  4051  00:50:27 
      Name                    Command               State                  Ports                
-----------------------------------------------------------------------------------------------
jenkins_data_1     echo Data container for Je ...   Exit 0                                      
jenkins_master_1   /bin/tini -- /usr/local/bi ...   Up       0.0.0.0:50000->50000/tcp, 8080/tcp 
jenkins_nginx_1    nginx                            Up       443/tcp, 0.0.0.0:80->80/tcp        
jenkins_slave_1    /bin/bash                        Exit 0                                      
 salahaddin@TulipanROG  ~/Proyectos/uzmantech/jenkins   rework ● ?         
```

And here my configuration:
![seleccion_282](https://cloud.githubusercontent.com/assets/5034215/19012354/6711757a-8778-11e6-8628-53b80775098e.png)

Good, my advances are this:
Yes, i have a new node, but, he doesn't connect.
![seleccion_280](https://cloud.githubusercontent.com/assets/5034215/19012358/779c0a7c-8778-11e6-8e1c-f781544012ea.png)

Trying search in log files, i haven't found any report, and in log within new node i have this:
![seleccion_281](https://cloud.githubusercontent.com/assets/5034215/19012361/a5a8344a-8778-11e6-81d2-d13b8dce992c.png)

``` html
Starting connection command for 605f28691ad4a5631a56a89576a2243d39a2a5bf83762c64e399c0ee3dee241d






HTTP ERROR 404

Problem accessing /computer/Local%20Docker%20Host%20Machine-605f28691ad4/logText/progressiveHtml. Reason:

    Not Found

Powered by Jetty://
```

What is my error now?

**Comment by maxfields2000** [comment]
I know this is old, but please comment if you can. Are you using Jenkins2 and the "Yet Another Docker Plugin" with JNLP set up? The only reason you should be calling back to Jenkins and getting a 404 is if you are.

For that to work, the Jenkins Location URL in the jenkins config has to be something you can route to from your Slave (which is making the HTTP call). Typically I use the IP Address of the Docker Host for this. And it i works, otherwise I get the error you descrbie above.

**Comment by SalahAdDin** [comment]
@maxfields2000 can you show us your steps? 

Yes, I'm using the latest `Jenkins` version, `2.53`, and `yet another docker plugin`. 

Thank you

**Comment by maxfields2000** [comment]
I've updated my entire Jenkins2 out of the box setup and reverified this.  Out of the box it now comes completely configured and ready to work (to avoid typo's/setup mistakes) so everything should just work now.

If you  need the image name in the future, on this new setup it's "jenkins2_slave".
