### ISSUE TITLE
I had to update JAVA_VERSION and JAVA_DEBIAN_VERSION in jenkins-master/Dockerfile

### ISSUE THREAD

**Issue by ScandyMark** [maxfields2000/dockerjenkins_tutorial#31]
$CMD docker-compose build
failed for me 2016_09Sep_28. 
I needed to update 

jenkins-master/Dockerfile:ENV JAVA_VERSION 8u102
jenkins-master/Dockerfile:ENV JAVA_DEBIAN_VERSION 8u102-b14.1-1~bpo8+1

**Comment by maxfields2000** [comment]
If you can, please post your entire dockerfile here if you want help changing the Jenkisn version.
