### ISSUE TITLE
Jenkins Credentials page doesn't seem to be proxied

### ISSUE THREAD

**Issue by drahamim** [maxfields2000/dockerjenkins_tutorial#35]
Not sure if this is an issue with this tutorial, jenkins, nginx or something I typed wrong somewhere. 
Please let me know if this was an issue made in error. 

I have to proxy due to some issues on my mac. 

I have setup the Docker files according to the repo except with a port forward in the docker compose file to port 8080 -> 80 for nginx. 

However when going to the credentials page the link seems to go to localhost not localhost:8080. 
All other pages seem to work.

**Comment by maxfields2000** [comment]
Oi, that's interesting. Not sure entirely how to replicate.  Check your Jenkins configuration and make sure that the Jenkins URL/Host is listed as using Port 8080.  Also make sure that the Manage Jenkins page is not complaining about reverse proxy being broken.

**Comment by drahamim** [comment]
It was all based on the tutorial files (Website not repo) I got around it by forwarding 80 to 80 on nginx  which seemed to fix it. But basically it was something like `jenkinshost:8080/` worked then clicked on configure and the url changed to `jenkinshost/configure` dropping the port number.

**Comment by maxfields2000** [comment]
Ah I suspect that was because I wasn't properly protecting the Jenkins Location settings somehow. I think I have this resolved in my latest Jenkins2 update. I've opted to leave the tutorial/blogs alone atm as I think about how to best update those blogs (they are a year or two old now!)

**Comment by maxfields2000** [comment]
This should be fixed in the blogs now as well, so going to close this :)
