### ISSUE TITLE
Any update plan of the tutorial for the Docker for Mac ?

### ISSUE THREAD

**Issue by johnwanggithub** [maxfields2000/dockerjenkins_tutorial#36]
Hi, firstly thanks a lot for writing the tutorial ! and I found the tutorial in jenkins2 is for local Docker-Toolbox version of a fully ephemeral jenkins environment(tested up to Docker 1.11). while now docker is 1.13 and docker for mac is ready. recently I tried a lot on docker(1.13) for mac and met some questions, such as: YADP plugin can not connect to docker damon in jenkins, no .docker under $home folder ..etc  so just wonder if there is plan for updating the tutorial which will be great help. thanks in advance

**Comment by maxfields2000** [comment]
There are! Sorry for the late response, I have a local version working on Docker for Mac, I just need to massage it and I'll get it up here t hen I plan to update the blog series or perhaps a slightly new blog referencing the evolutionary changes. Trying to get ahead of all the new Jenkins 2 stuff.

**Comment by maxfields2000** [comment]
(Give me until next week to iron out the details and make sure everything is easy to understand, conceptually the problem with Docker for Mac is that it doesn't natively listen on a port, it only uses the docker.sock file, so I found an awesome proxy container I use to proxy the sock file to a port locally to work around it.  "ehazzlet/docker-proxy" is really easy to use and I'll  probably add that as part of the base configuration.).

**Comment by rahulakash** [comment]
Hi @maxfields2000, thank you for this awesome repo. Any updates on the tutorial for 'Docker for Mac'? It would be very helpful.

**Comment by maxfields2000** [comment]
@rahulakash Updated! Take a look at the new "jenkins2" folder, it should be fully compatible with Docker for Mac (tested by many folks for me). Worked around Docker for Mac not having a native Docker TLS setup by using Evan Hazzlet's awesome docker-proxy container to proxy the docker socket file.  Works for Docker-toolbox as well!
