### ISSUE TITLE
Full home partition warning in Jenkins

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#37]
Hi, i made my own docker images and compose file and mounted all structure in my computer.

All is well.

But i have a warning in jenkins that say me the home partition is full:
![seleccion_318](https://cloud.githubusercontent.com/assets/5034215/24868223/08964fc0-1e18-11e7-84cc-4482a74c6ad1.png)

Why happen this?

Reviewing this in your image, compling this repository, i foun a problem: I'd installed `BlueOcean` plugin, is heavy, and it ate the home space. But i can't understand this. We create a external data volume for avoid it, but this plugin eat all space, why?

**Comment by maxfields2000** [comment]
I'm not sure why that would happen. I've currently got a local version of Jenkins 2 running with Blue Ocean. The partitions should have plenty of space.

Can you remote into your docker container (docker exec) and do a "df -kh" at the root folder and see what comes back?

Also are you using Docker for mac, Docker Toolbox or Docker for Windows? Or some other solution?

**Comment by SalahAdDin** [comment]
Docker in Linux. I'll review then.
