### ISSUE TITLE
Can't seem to upgrade the jenkins version

### ISSUE THREAD

**Issue by drahamim** [maxfields2000/dockerjenkins_tutorial#38]
I changed the version of jenkins as the tutorial lists a very old version. However when changing the Jenkins_version number and the Jenkins_sha value it seems to not be able to start the docker container. 

I had changed the values to 2.46.1 and the acumpaning sha256 (which I changed the sha check in the docker file to match)

**Comment by SalahAdDin** [comment]
Can you put the trace back here?

**Comment by maxfields2000** [comment]
Yea I'd like to see it. Sometimes for testing I remove the SHA check and just do the download. Also post your current dockerfile if you can.

**Comment by drahamim** [comment]
I should comment at this point that what I did was download the current Repo Version of the Jenkins-master Dockerfile and that fixed it. 
What I had done is use the old version with 1.625.3 (I think that was the jenkins version number) and had simply changed the values. I can try and reproduce and find the trace but when running the `make run` command it would say it was starting the nodes and then `docker ps ` would show no nodes active.
