### ISSUE TITLE
Question: Run docker (docker-compose) inside slaves?

### ISSUE THREAD

**Issue by chucky2305** [maxfields2000/dockerjenkins_tutorial#39]
How can i run docker or even docker-compose inside of a slave?

Kind regards,
Max

**Comment by maxfields2000** [comment]
You have a couple of choices.  First you'd have to install the Docker Client and Docker-Compose into your Dockerfile for the slave image.

Next you need to decide what DockerHost you want to use. I typically have a seperate dockerhost running for that. You can however use your own dockerhost, you'd have to modify The docker slave template in the Jenkins config to mount /var/run/docker.sock into every container you run, then you could use the local docker socket to make your "Docker build" calls.  OR if you know the IP of your dockerhost (in the demos case it's your local desktop) just set your DOCKER_HOST environment variable to that port. If you're using Docker TLS you'd have to have the docker cert keys as well.
