### ISSUE TITLE
jenkins.model.JenkinsLocationConfiguration.xml: No such file or directory

### ISSUE THREAD

**Issue by dhanugupta** [maxfields2000/dockerjenkins_tutorial#41]
Hi

Have you encountered this issue:
sed: can't read /var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml: No such file or directory

after i start the docker container, getting this error?

**Comment by maxfields2000** [comment]
The startup scripts in the system attempt to write the IP address they obtain from you on first start to this config file (where Jenkins keeps the IP address).  If this file is missing you'll get the error you describe though that file should be baked into the build process. It should be packed into the tar.gz for configuration data an uncompressed/unpackaged during the docker build run. 

I would try to rebuild everything by

```
make stop
make clean-data
make build
make run
```

**Comment by dhanugupta** [comment]
Thanks cleaning up the process worked !!

**Comment by dhanugupta** [comment]
Any idea how to enable localhost 25 for smtp send email so that jenkins can send email?
currently only 8080,50000 ports are opened, trying to get the smtp send email working inside the docker container.
