### ISSUE TITLE
Scriptler plugin distribution is suspended.

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#42]
See: https://wiki.jenkins-ci.org/display/JENKINS/Scriptler+Plugin

**Comment by maxfields2000** [comment]
Yea I've seen this. You can still install the plugin (I still do). We operate on a private Network internally and don't have an exposed Jenkins server, and we utilize Scriptler to create additional API's in Jenkins.  

There is a new version coming soon finally that should address the security concerns.  For now, caveat emptor, I would not advise deploying Scriptler on a Jenkins server that is publicly available until the fixes come out.
