### ISSUE TITLE
Docker Ip Address working in Linux 

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#43]
I see that you implements a `ip` localization. It will be work very fine in `windows` and `osx` but in linux isn't needed.

I try to use my localhost ip but it doesn't works.

Which have to be `docker ip` address in a linux dev environment?

**Comment by SalahAdDin** [comment]
@maxfields2000 Yes, this give me an error:

I put originally the `localhost` host: `127.0.0.1`, but it didn't works, so i decided review in internet for get my host ip:
```
 ip r | awk '/default/{print $3}'                    ✓  1778  15:40:02 
10.27.0.1
 salahaddin@TulipanROG  ~/Proyectos/UzmanTech/jenkins/jenkins  master ●   netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}'
10.27.0.1
```

I put then this ip but it doesn't work yet:
![deepinscreenshot20170608154918](https://user-images.githubusercontent.com/5034215/26929478-8456773e-4c62-11e7-8308-d650e36c0e0a.png)

And now with other options:
```bash
docker inspect jenkins_master_1 | grep IP         1 ↵  1787  15:48:15 
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
```
Same result.

Finally reviewing my `ip` configuration:
```
ifconfig docker0                                    ✓  1805  16:01:37 
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:8eff:fe7c:58cb  prefixlen 64  scopeid 0x20<link>
        ether 02:42:8e:7c:58:cb  txqueuelen 0  (Ethernet)
        RX packets 202059  bytes 22029742 (21.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 378810  bytes 521715610 (497.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

`inet` option is the same that i get doing:
```bash
docker inspect  --format '{{ .NetworkSettings.Gateway }}' jenkins_master_1 
172.17.0.1
 salahaddin@TulipanROG  ~/Proyectos/UzmanTech/jenkins/jenkins  master ●  docker inspect  --format '{{ .NetworkSettings.IPAddress }}' jenkins_master_1
172.17.0.4
```

And finally.....:
![deepinscreenshot20170608160424](https://user-images.githubusercontent.com/5034215/26929923-2d1e3d38-4c64-11e7-92e9-0dd7bb7d30b8.png)
Nothing.

And ensure me about it:
![deepinscreenshot20170608160850](https://user-images.githubusercontent.com/5034215/26930076-cd535a5e-4c64-11e7-8438-d9c3b62cd3c3.png)
![deepinscreenshot20170608160625](https://user-images.githubusercontent.com/5034215/26930023-a6b0aaf0-4c64-11e7-8a6d-0eb23dc6b16c.png)
![deepinscreenshot20170608160638](https://user-images.githubusercontent.com/5034215/26930031-ac227e32-4c64-11e7-927a-2a8f61938a40.png)
![deepinscreenshot20170608160725](https://user-images.githubusercontent.com/5034215/26930032-ae854704-4c64-11e7-912e-1c4abb7151e3.png)


What's wrong?

**Comment by willis7** [comment]
I'm hitting this same issue with Mac. I can see that the Docker API is available because I get a response in my browser with `http://localhost:3375/images/json`.

How are others not getting this issue?

**Comment by willis7** [comment]
For those of you who end up here (like me).... one way you can find the host ip is running the following command:

`docker run --net=host debian:jessie ip addr show | grep 192`

You will get an output like:

```
inet 192.168.65.3/24 brd 192.168.65.255 scope global eth0
```
My ip in this case would be `192.168.65.3`. If you use that in the Jenkins configuration and test, you should get a successful connections.

**Comment by SalahAdDin** [comment]
@willis7 I will test it, thank you.

**Comment by maxfields2000** [comment]
I have a fix for this coming soon in my branch that will no longer require you to use a local IP like this by leveraging docker networking, sorry for the pain folks that this isn't obvious.

**Comment by maxfields2000** [comment]
This should now be fixed in the latest version on master, no need to provide a local IP (unless running on Docker for Windows and then only in the jenkins config for the Dockerhost).
