### ISSUE TITLE
It seems that reverse proxy settings is wrong

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#44]
Is a strong error now:
![deepinscreenshot20170608131112](https://user-images.githubusercontent.com/5034215/26923972-837ae3c4-4c4c-11e7-876a-3ccb6246573d.png)

Clicking in `More Info` button, i'm redirected to this page: `https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+says+my+reverse+proxy+setup+is+broken`

Which the problem with the settings?

I'm using the basic configuration files from this repository. Thanks.

**Comment by maxfields2000** [comment]
This should be fixed in the latest blog updates and on master (Jenkins should not be complaining about a bad reverse proxy), when using the out of box setup.  Please feel free to re-open if you encoutner this or other new isseus.
