### ISSUE TITLE
Some aclaration notes

### ISSUE THREAD

**Issue by SalahAdDin** [maxfields2000/dockerjenkins_tutorial#45]
I'm testing this comfiguration; after many plugins additions i have a good performance, except for some minor bugs, all is well.

In this case i want ask about this warning:
```bash
You no longer need to configure Docker TLS keys, this setup runs a "Proxy" container against your docker host that works around the TLS security. PLEASE NOTE: DO NOT USE IN PRODUCTION. This is a convenience proxy to make sure things work out of the box on Docker-toolbox, Docker for Mac or Docker for Windows without fuss!
```

In the production case which is the better setup?

**Comment by maxfields2000** [comment]
So this is a good set up for local. If you move to production I'd recommend setting up TLS keys on your Docker endpoint (or finding some other way to secure traffic between jenkins and docker). You don't want production docker hosts listening on publicly accessible ports unless you can really garauntee your network is very secure.
