### ISSUE TITLE
Jenkins Cert part is now different

### ISSUE THREAD

**Issue by RyanSpartan117** [maxfields2000/dockerjenkins_tutorial#48]
Hey,

Firstly, Brilliant tutorial! Good to get some insight.

Been struggling with the "SETUP DOCKER CERTIFICATE DIRECTORY" part from: https://engineering.riotgames.com/news/jenkins-ephemeral-docker-tutorial

Specifically: "Docker Certificates Directory" doesn't appear on the drop down list. Couldn't work out how to add the certificates with the new set of options on Jenkins (attached).
<img width="770" alt="screen shot 2018-01-16 at 5 07 47 pm" src="https://user-images.githubusercontent.com/28562219/35001902-e149ebac-fadf-11e7-9eef-037e7b644c2c.png">

Any help in using the new Jenkins is greatly appreciated.

Kind Regards,

Ryan

**Comment by maxfields2000** [comment]
Going to close this issue I now have a new PR that avoids needing to use these Jenkins certs entirely. There will be a new blog as well. Check out the "blog_refresh" branch if it's not yet submitted to master.
