### ISSUE TITLE
chown cannot work due to base image executing VOLUME command

### ISSUE THREAD

**Issue by jimzucker** [maxfields2000/dockerjenkins_tutorial#7]
@maxfields2000 I put in the 'best practice items per this article: https://engineering.riotgames.com/news/putting-jenkins-docker-container
I think the advice is pretty good, but since the image from cloudbees calls the VOLUME Command this has to be updated to work, please review my example maybe I translated it incorrectly.

@rtyler can you review, maybe this steps and see if you think they are best practice or I should remove them and not worry about them..
# Create a log for jenkins (best practice) per Mayfield Stewart

RUN mkdir /var/log/jenkins
RUN chown -R jenkins:jenkins /var/log/jenkins
RUN mkdir /var/cache/jenkins
RUN chown -R jenkins:jenkins /var/cache/jenkins
ENV JAVA_OPTS -Xmx8192m
ENV JENKINS_OPTS --handlerCountStartup=100 --handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war

Example: https://github.com/capitalone/Hygieia/tree/master/test-servers/jenkins

But on my image it does work, maybe I am doing something wrong but I think we issue due to permissions as the VOLUME command is run in the base image so the clowns above dont work.. I think this all has to be in the extension point.

**Comment by maxfields2000** [comment]
This is interesting I'll have to take a look at whats going on. It definitely works for me in all my local builds I've done.

What version of Docker are you using?
